impact_groups = {
    "adjective_term_book_related": {
        "terms": [
            "aangenaam",
            "aardig",
            "abrupt",
            "absurd",
            "actueel",
            "agressief",
            "alleraardigst",
            "amusant",
            "apart",
            "authentiek",
            "bewonderenswaardig",
            "bewonderingswaardig",
            "bijzonder",
            "bombastisch",
            "buitengewoon",
            "chapeau",
            "claustrofobisch",
            "cool",
            "creatief",
            "creepy",
            "cynisch",
            "diepzinnig",
            "doodeng",
            "dramatisch",
            "dromerig",
            "droog",
            "duidelijk",
            "echt",
            "eentonig",
            "eerlijk",
            "elegant",
            "eng",
            "ergerlijk",
            "esthetisch",
            "euforisch",
            "fantasierijk",
            "fantasievol",
            "fantastisch",
            "fijn",
            "fijngevoelig",
            "flauw",
            "fraai",
            "frappant",
            "gaaf",
            "geestig",
            "geinig",
            "gek",
            "geloofwaardig",
            "geniaal",
            "gevoelig",
            "gevoelvol",
            "geweldig",
            "grappig",
            "griezelig",
            "groots",
            "gruwelijk",
            "harmonisch",
            "hartstikke",
            "hartverscheurend",
            "hartverwarmend",
            "heerlijk",
            "heftig",
            "herkenbaar",
            "hilarisch",
            "hoogstaand",
            "huiveringwekkend",
            "humoristisch",
            "informatief",
            "interessant",
            "intriest",
            "inzichtelijk",
            "ironisch",
            "irritant",
            "klankrijk",
            "knap",
            "komisch",
            "kunstig",
            "langdradig",
            "leerrijk",
            "leerzaam",
            "leesbaar",
            "lelijk",
            "leuk",
            "leuke",
            "levensecht",
            "liefelijk",
            "literair",
            "luguber",
            "lyrisch",
            "maatschappijkritisch",
            "markant",
            "matig",
            "meesterlijk",
            "melancholiek",
            "melancholisch",
            "melodieus",
            "melodisch",
            "metaforisch",
            "misplaatst",
            "mooi",
            "morbide",
            "onduidelijk",
            "ongeloofwaardig",
            "ongemakkelijk",
            "onprettig",
            "onvergetelijk",
            "onverwacht",
            "onweerstaanbaar",
            "onwijs",
            "oppervlakkig",
            "origineel",
            "overzichtelijk",
            "perfect",
            "pijnlijk",
            "plezant",
            "plezierig",
            "poëtisch",
            "prachtig",
            "pregnant",
            "prettig",
            "puntig",
            "puur",
            "raadselachtig",
            "raak",
            "realistisch",
            "ritmisch",
            "romantisch",
            "saai",
            "sarcastisch",
            "satirisch",
            "schattig",
            "sentimenteel",
            "sfeervol",
            "slordig",
            "smakeloos",
            "spijtig",
            "spits",
            "spitsvondig",
            "stilistisch",
            "subliem",
            "super",
            "surrealistisch",
            "surreeel",
            "sympathiek",
            "tof",
            "tragisch",
            "triest",
            "troosteloos",
            "uitzonderlijk",
            "vermakelijk",
            "verrukkelijk",
            "verschrikkelijk",
            "vertrouwd",
            "verwarrend",
            "vlijmscherp",
            "vlot",
            "voelbaar",
            "volmaakt",
            "voorspelbaar",
            "walgelijk",
            "wansmakelijk",
            "wonderbaarlijk",
            "zalig",
            "zielig",
            "zinvol",
            "humorvol",
            "poetisch"
        ]
    },
    "adjective_term_reader_related": {
        "terms": [
            "angstig",
            "bang",
            "benauwd",
            "benieuwd",
            "beroerd",
            "bewust",
            "blij",
            "boos",
            "dankbaar",
            "doodsbenauwd",
            "droef",
            "droevig",
            "eerbiedig",
            "emotioneel",
            "empathisch",
            "enthousiast",
            "gelukkig",
            "koud",
            "kwaad",
            "misselijk",
            "nieuwsgierig",
            "nostalgisch",
            "onrustig",
            "onverschillig",
            "stil",
            "stomverbaasd",
            "tevreden",
            "treurig",
            "verdrietig",
            "vrolijk",
            "warm",
            "woedend",
            "zenuwachtig"
        ]
    },
    "noun_continuous_phrase": {
        "terms": [
            "(alle moeite|de moeite) (waard)",
            "(belangstelling) (gewek*|wek*)",
            "(brok) (in) (me|mijn|m'n|je) (keel)",
            "(gewek*|wek*) belangstelling",
            "(je|ik) (afsluit|afgesloten) (*wereld)",
            "(kromme tenen)",
            "(tijd) (vliegt)",
            "(tranen) (in) (de|me|mij|mijn|m'n) (ogen)",
            "(uit)(je|me|mijn)(evenwicht)",
            "als een trein",
            "andere wereld",
            "bij (de|je|mijn) strot",
            "brok in de keel",
            "diep* betek*",
            "droge humor",
            "educatieve waarde",
            "eye opener",
            "geen fan van",
            "hoger (plan|niveau)",
            "in (een|één) zucht",
            "in (zijn|z'n|haar|m'n|mijn|je) (greep|grip)",
            "in de war",
            "knoop in (me|mijn|m'n|je) maag",
            "lang van stof",
            "lange adem",
            "meer dan waard",
            "met open mond",
            "op (grootse|niet mis te verstane) wijze",
            "op het puntje van (me|mijn|m'n|je) stoel",
            "open en eerlijk",
            "stof tot nadenken",
            "verplichte kost",
            "voer voor",
            "zucht van verlichting"
        ]
    },
    "noun_discontinuous_phrase": {
        "terms": [
            "(draad) (kwijt*)",
            "(een andere) (bril|blik|kijk)"
        ]
    },
    "noun_term_book_related": {
        "terms": [
            "aanrader",
            "afbreuk",
            "afkeer",
            "amusement",
            "beknoptheid",
            "beslag",
            "boodschap",
            "cliche",
            "cliché",
            "compliment",
            "diepgang",
            "drama",
            "duidelijkheid",
            "elegantie",
            "fascinatie",
            "fijngevoeligheid",
            "gedachte",
            "gemis",
            "genoegen",
            "humor",
            "idee",
            "laag",
            "levensles",
            "metafoor",
            "metaforiek",
            "mokerslag",
            "moois",
            "onderwerp",
            "opbouw",
            "overtuiging",
            "parel",
            "pareltje",
            "perfectie",
            "pracht",
            "realisme",
            "satire",
            "schrijfstijl",
            "sneltreinvaart",
            "spanning",
            "speciaals",
            "spitsvondigheid",
            "spot",
            "stijl",
            "stimulans",
            "taalgebruik",
            "teleurstelling",
            "thema",
            "tragedie",
            "triestheid",
            "twijfel",
            "uitwerking",
            "verademing",
            "verbeelding",
            "vermaak",
            "verrassing",
            "verrijking",
            "wansmaak",
            "woordgebruik",
            "zinnen",
            "zinsbouw",
            "zinsgebruik",
            "zonde"
        ]
    },
    "noun_term_reader_related": {
        "terms": [
            "achting",
            "argwaan",
            "belangstelling",
            "bevrediging",
            "bewondering",
            "buikpijn",
            "cynisme",
            "diepzinnigheid",
            "droefenis",
            "droefheid",
            "eerbied",
            "emotie",
            "empathie",
            "energie",
            "ergernis",
            "genot",
            "gevoel",
            "herkenning",
            "hoofdpijn",
            "huivering",
            "inspiratie",
            "interesse",
            "ironie",
            "irritatie",
            "jeuk",
            "kippenvel",
            "knuffel",
            "kriebel",
            "lachsalvo",
            "medelijden",
            "melancholie",
            "nieuwsgierigheid",
            "nostalgie",
            "onduidelijkheid",
            "ontspanning",
            "ontzag",
            "plezier",
            "rilling",
            "sarcasme",
            "schaterlach",
            "sentiment",
            "spijt",
            "sympathie",
            "tevredenheid",
            "treurigheid",
            "verbazing",
            "verrukking",
            "vervoering",
            "verwondering",
            "walging",
            "weerzin",
            "worsteling",
            "zenuwen",
            "glimlach",
            "lach",
            "lach (en|of) een traan"
        ]
    },
    "other": {
        "terms": [
            "*zucht*",
            "helaas",
            "jammer",
            "mee in",
            "proficiat",
            "zucht dicht"
        ]
    },
    "partic_desc": {
        "terms": [
            "beklijvend",
            "beschreven",
            "betoverend",
            "dwingend",
            "geformuleerd",
            "geschreven",
            "ingeleefd",
            "omschreven",
            "opvallend",
            "verwoord"
        ]
    },
    "partic_term": {
        "terms": [
            "aangegrepen",
            "aangespoord",
            "aangrijpend",
            "aansprekend",
            "adembenemend",
            "afwisselend",
            "angstaanjagend",
            "beangstigend",
            "bedrukkend",
            "beklemmend",
            "beknopt",
            "bekoord",
            "benauwend",
            "betoverd",
            "bevredigend",
            "bijtend",
            "bloedstollend",
            "boeiend",
            "choquerend",
            "confronterend",
            "deprimerend",
            "diepgaand",
            "dreigend",
            "fascinerend",
            "geboeid",
            "gechoqueerd",
            "geconfronteerd",
            "geëmotioneerd",
            "geergerd",
            "geërgerd",
            "gefascineerd",
            "gefrustreerd",
            "gegniffeld",
            "gegrepen",
            "gegrinnikt",
            "geinspireerd",
            "geirriteerd",
            "gekluisterd",
            "gekwetst",
            "gelaagd",
            "geleerd",
            "gepakt",
            "geprikkeld",
            "geraakt",
            "geroerd",
            "geschokt",
            "gestoord",
            "hoopgevend",
            "imponerend",
            "indringend",
            "indrukwekkend",
            "innemend",
            "inspirerend",
            "intrigerend",
            "kwetsend",
            "meegenomen",
            "meegesleept",
            "meegesleurd",
            "meegetrokken",
            "meegevoerd",
            "meegezogen",
            "meeslepend",
            "ondergedompeld",
            "onderhoudend",
            "onthecht",
            "onthutsend",
            "ontluisterend",
            "ontroerd",
            "ontroerend",
            "ontspannend",
            "ontwapenend",
            "ontzettend",
            "opgebouwd",
            "opgeroepen",
            "opgezogen",
            "opwekkend",
            "opwindend",
            "overtuigend",
            "overweldigd",
            "overweldigend",
            "pakkend",
            "prikkelend",
            "roerend",
            "rustgevend",
            "schitterend",
            "schokkend",
            "schrijnend",
            "schurend",
            "shockerend",
            "spannend",
            "spottend",
            "stimulerend",
            "storend",
            "teleurgesteld",
            "treffend",
            "uitdagend",
            "uitgewerkt",
            "uitstekend",
            "vastgekluisterd",
            "veeleisend",
            "verbaasd",
            "verbijsterd",
            "verbijsterend",
            "verbluffend",
            "verdiend",
            "verfrissend",
            "verhelderend",
            "vermaakt",
            "vermoeiend",
            "vernieuwend",
            "verontrustend",
            "verpletterd",
            "verpletterend",
            "verrassend",
            "verrijkt",
            "verrukt",
            "verslavend",
            "versteld",
            "verstikkend",
            "verstild",
            "verstomd",
            "verveeld",
            "vervelend",
            "verwacht",
            "verwarrend",
            "vloeiend",
            "weerzinwekkend",
            "welluidend",
            "zenuwslopend",
            "zinderend",
            "emotionerend",
            "geïnspireerd",
            "teleurstellend"
        ]
    },
    "verb_continuous_phrase": {
        "terms": [
            "(bedenk|bedacht) (me)",
            "(dit|dat|het) geeft",
            "(dwong|dwongen|dwingt|dwingen) (me|mij|je|de lezer)",
            "(hebben|heeft) er voor gezorgd",
            "(hebben|heeft) ertoe geleid",
            "(hebben|heeft) ervoor gezorgd",
            "(ik|je) (hoop|hoopt)",
            "(ik|je) (merk|merkt)",
            "(ik|je) weet nu",
            "(ik|je|lezer) leef* mee",
            "(ik|je|lezer) voel* (mee|met)",
            "(je|ik) (waan.*) (je|jezelfme|mij|mezelf|mijzelf)",
            "(lijkt|leek) het",
            "(nogmaals) (lezen)",
            "(uitkijken|verlangen) naar",
            "(waan.*) (je|ik) (je|jezelfme|mij|mezelf|mijzelf)",
            "besef van tijd",
            "betekenis (krijgt|krijgen)",
            "diep gaan",
            "doet me veel",
            "gemakkelijk te lezen",
            "goed (geschreven|omschreven|beschreven)",
            "goed gedaan",
            "had wat mij betreft",
            "heeft me zoveel gedaan",
            "heen en weer geslingerd",
            "het (lijkt|leek)",
            "het schrijnt",
            "het schuurt",
            "het wringt",
            "in het verhaal opgenomen",
            "in te leven",
            "leeft mee met",
            "leidt je",
            "lezer waant (zich|zichzelf)",
            "makkelijk geschreven",
            "niet meer stoppen",
            "onder de indruk",
            "opgenomen in het verhaal",
            "sleep* (je|me) mee",
            "stoppen met lezen",
            "te geloven",
            "terugdenken aan",
            "volledige aandacht",
            "vond er (niets|weinig) aan",
            "weten hoe het afloopt"
        ]
    },
    "verb_discontinuous_phrase": {
        "terms": [
            "(aandacht) (trekken)",
            "(aandacht) (vasthou*|vasthie*)",
            "(aandacht) (verliezen|verloor|verloren)",
            "(aandacht) (verslappen)",
            "(anders|beter|negatiever|positiever|slechter|vrolijker|zonniger) (uitzien|uitziet)",
            "(bij de keel) (grijpen|grijpt|greep|grepen|gegrepen)",
            "(blijft|blijven) (een raadsel)",
            "(blijft|blijven|bleef|bleven) (je|me|mij) (bij)",
            "(daagt) (me|ons|je|lezer) (uit)",
            "(doet|deed) wat met (je|me|mij)",
            "(doet|doen) (me|mij|je) (denken aan)",
            "(doet|doen) (me|mij|je) (verlangen naar)",
            "(droom*) (weg)",
            "(geeft|geven|gegeven|biedt|bieden|geboden|vergaart|vergaard|krijgt|krijgen|gekregen|vergaren|ontstaat|ontstaan) (inzicht|inzichten)",
            "(gelezen) (moet|moeten) (hebben)",
            "(grijpt|grijpen|greep|grepen) (bij) (de|je|me|mijn|m'n) (keel)",
            "(het) (nadeel) (is|blijft)",
            "(houdt) (me|mij|je) (bij de les)",
            "(houdt|houden) (je|me|mij|de lezer) (vast)",
            "(houdt|houden) (je|me|mijn|m'n) (aandacht) (vast)",
            "(houdt|houden) (me|mij|je|de lezer) (in de ban|in haar ban|in haar macht|in zijn macht|in spanning|gespannen)",
            "(houdt|houden) (me|mij|je|de lezer) (in een wurggreep|gekluisterd)",
            "(houdt|houden) (me|mij|je|de lezer) (uit) (m'n|mijn|je|zijn|z'n|haar|de) (slaap)",
            "(houdt|houden) (me|mij|je|de lezer|ons) (een spiegel voor)",
            "(houdt|houden|hield|hielden) (de lezer|me|mij|je) (bezig)",
            "(houdt|houden|hield|hielden) (me|mij|je|de lezer) (alert|scherp|geboeid|aan het lezen)",
            "(ik vind|vind ik) (het) (een) (boek)",
            "(ik wilde|je wilt|wil je) (weten)",
            "(ik|je|lezer) (verbonden)",
            "(in) (een|1) (adem|avond|keer|ruk|stuk|zucht) (gelezen|uitgelezen)",
            "(jammer) (afgelopen)",
            "(je|ik) (je|jezelfme|mij|mezelf|mijzelf) (waan.*)",
            "(je|ik) (zat|zit) (in het verhaal)",
            "(je|me|mij) (niet) (losliet|loslieten|losgelaten)",
            "(komt|komen) (op) (me|mij) (over)",
            "(komt|komen) (over)",
            "(krijg|krijg) (geen|niet) (genoeg van)",
            "(laat|liet|lieten) (mij|me|je|lezer) (niet) (los)",
            "(leef*) (in) (wereld)",
            "(leest|las) (in) (een|1) (adem|avond|ruk|zucht) (uit)",
            "(liepen tranen|liepen de tranen|tranen liepen) (over mijn wangen)",
            "(liet|laat|laten)(je|ons|me|lezer)(koud)",
            "(maakt|maken) (duidelijk|inzichtelijk)",
            "(me|m'n|mijn|je) (hart) (gestolen)",
            "(mezelf|jezelf) (verliezen)",
            "(moet) (diep|goed|lang|veel) (nadenken)",
            "(moet) (me|mijn|m'n|je) (hoofd) (erbij houden)",
            "(moet|moeten) lezen",
            "(neem*|nam) (je|me|lezer|ons) (mee)",
            "(op) (zijn|haar|hun) (plek|plaats) (valt|vallen|viel|vielen)",
            "(open*) (me|je|mij) (ogen)",
            "(raakt|raken|raakte|raakten) (me|mij|je|lezer)",
            "(roept|riep) (beelden) (op)",
            "(roept|riep) (gevoel|gevoelens|glimlach|weemoed|tederheid|emotie|emoties) (op)",
            "(roept|riep) (herinneringen) (op)",
            "(roept|riep) (sfeer) (op)",
            "(roept|riep) (vragen) (op)",
            "(sleep*|sleur*) (je|me|lezer|ons) (mee)",
            "(spreekt|spreken|sprak|spraken) (me) (aan)",
            "(staan de tranen in) (me|mijn|m'n|je) (ogen)",
            "(staan de tranen) (me|mij|je) (in de ogen)",
            "(valt|vallen|viel|vielen) (op) (zijn|haar|hun) (plek|plaats)",
            "(vergat|vergeten|vergeet) (alles om (me|je|mij) heen)",
            "(voer*) (je|me|lezer|ons) (mee)",
            "(wekt|wekken) (de indruk)",
            "(wekt|wekken) (de suggestie)",
            "(wordt) (lastiger)",
            "(worstel|worstelt|worstelen|worstelde|worstelden) (met|door)",
            "(zat|zit) (je|ik) (in het verhaal)",
            "(zet aan|aanzet) (tot nadenken)",
            "(zet|zetten|zette) (de lezer|je|me|mij) (aan het denken)",
            "(zien|ziet|zag) (voor) (me|mij|je)",
            "(zou|zouden) (moeten) (hebben|lezen)",
            "je (wil|wilt|willen) lezen",
            "voor (me|mij|je) (zien|ziet|zag)"
        ]
    },
    "verb_term": {
        "terms": [
            "aanbevelen",
            "aangrijpen",
            "aanraden",
            "aansporen",
            "aanzetten",
            "absorberen",
            "afschrikken",
            "amuseren",
            "bedenken",
            "behagen",
            "beklemmen",
            "beklijven",
            "bekoren",
            "belonen",
            "bereiken",
            "beroeren",
            "bescheuren",
            "beschrijven",
            "bevallen",
            "bewonderen",
            "boeien",
            "bulderen",
            "confronteren",
            "doorbreken",
            "enthousiasmeren",
            "ergeren",
            "fascineren",
            "formuleren",
            "frustreren",
            "gelachen",
            "genieten",
            "genoten",
            "glimlachen",
            "gniffelen",
            "grijpen",
            "grinniken",
            "herkennen",
            "huilen",
            "indenken",
            "inleven",
            "irriteren",
            "kluisteren",
            "lachen",
            "leren",
            "lonen",
            "meebeleven",
            "meedenken",
            "meekijken",
            "meeleven",
            "meenemen",
            "meeslepen",
            "meesleuren",
            "meevoelen",
            "meevoeren",
            "meezuigen",
            "missen",
            "omschrijven",
            "ontroeren",
            "ontspannen",
            "opwekken",
            "overdonderen",
            "overtuigen",
            "overweldigen",
            "pakken",
            "prikkelen",
            "proeven",
            "schaterlachen",
            "schokken",
            "schrijven",
            "shockeren",
            "stimuleren",
            "stoorde",
            "storen",
            "vastpakken",
            "verbazen",
            "verbijsteren",
            "verliezen",
            "vermaken",
            "verontrusten",
            "verplaatsen",
            "verrassen",
            "verrijken",
            "vervelen",
            "verwoorden",
            "wegdromen",
            "wegleggen",
            "zeuren",
            "emotioneren",
            "inspireren"
        ]
    }
}


atomic_context_definitions = {
    "i_you": [r"\b(ik|je|jij)\b"],
    "me_you_reader": [r"\b(me|mij|mijn|m'n|je|jezelf|u|uzelf|ons|de lezer|lezers|zich)\b"],
    "adjective_reader_affect": [
        r"\b(ik|je) (ben|word|wordt|werd|raak|raakt|raakte) .*?\b{IMPACT_TERM}\b",
        r"\b(ik|je) .*?\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je) .*?\b{IMPACT_TERM}\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (er|hier) .*?\b{IMPACT_TERM} (van|door)\b",
        r"\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je|de lezer) (er|hier)(van| van|door| door)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (ben|bent|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(zal|zult|zullen) (er|hier) .*?\b{IMPACT_TERM}\b.*? (van|door) (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(zal|zult|zullen) .*? (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (zal|zult|zullen) (zijn|worden|raken)\b",
        r"\b(maakt|maken|maakte|maakten) (me|mij|je|de lezer) .*?\b{IMPACT_TERM}\b",
        r"\b(me|mij|je|de lezer) .*?\b{IMPACT_TERM}.*?\b(maakt|maken|maakte|maakten)\b",
        r"\b(krijg|krijgt|krijgen|kreeg) het .*?\b{IMPACT_TERM}\b",
        r"\b(voel|voelt|voelen|voelde) (me|mij|je) .*?\b{IMPACT_TERM}\b",
        r"\b{IMPACT_TERM}\b.*?(voel|voelt|voelen|voelde) (ik|je) (me|mij|je)\b",
        r"\b(me|mij|je) .*?\b{IMPACT_TERM} .*?\b(voel|voelt|voelen|voelde)\b",
        r"\been .*?{IMPACT_TERM}.*? gevoel\b",
    ],
    "book_aspect": [
        r"\b(\S*boek|\S*roman|\S*leesvoer|tekst|oeuvre|\S*bundel\S*)\b",
        r"\b(karakter\S*|personage\S*|hoofdperso\S*)\b",
        r"\b(ik-|hoofd|centrale|vader|moeder) *(figuur|figuren)\b", # can have one or more whitespaces
        r"\b(\S*verhaal|verhaallijn\S*|einde|situatie\S*|gebeurtenis\S*|plot|moment\S*|\S*passage\S*|\S*thema\S*)\b",
        r"\b(\S*portret\S*|tijdsbeeld|decor|\S*kroniek|\S*onderwerp\S*|\S*sfeer\S*)\b",
        r"\b(\S*stijl|verwoord\S*|taalgebruik|handelsmerk)\b",
        r"\b(\S*schrijver|\S*schrijfster|\S*auteur\S*)\b",
        r"\b(geschreven|schrijft|neerpennen|neergepend|opgetekend\S*)\b",
        r"\b(\S*schets\S*|tekenend|typer\S*|karakterise\S*|neerzetten|neergezet)\b",
        r"\b(afloop*|aflopen|climax|\S*element\S*|hoofdlijn\S*|hoogtepunt\S*|ontknoping\S*|opbouw\S*)\b",
        r"\b(relaas|stramien|\S*scene\S*|\S*scenario\S*|steekspel|slotakkoord|slotstuk|slot|waargebeurd)\b",
    ],
    "reading_aspect": [
        r"\b(lees|leest|lezen|las|lazen)\b",
    ],
}


def make_atomic_context_set(atomic_contexts):
    return [[definition] for context in atomic_contexts for definition in atomic_context_definitions[context]]

default_context_definitions = ["i_you", "me_you_reader", "book_aspect", "reading_aspect"]
impact_contexts = {
    "default": make_atomic_context_set(default_context_definitions),
    "adjective_term_reader_related": make_atomic_context_set(default_context_definitions + ["adjective_reader_affect"]),
}

