impact_groups = {
    "adjective_term_book_related": {
        "terms": [
            "abrupt*", "alleraardigst*", "aardig*",
            "authentiek*", "aangrijpend*", "aansprekend*",
            "beangstigend*", "beklemmend*", "benauwend*", "boeiend*",
            "choquerend*", "confronterend*", "deprimerend*", "dreigend*", "doodeng*",
            "echt*", "eentonig*", "eerlijk*", "eng*",
            "fascinerend*", "geestig*", "grappig*", "gek*",
            "geloofwaardig*", "groots*",
            "hartverwarmend*", "hartverscheurend*", "herkenbaar*", "herkenbare",
            "hilarisch*", "humoristisch*",
            "indringend*", "indrukwekkend*", "inspirerend*",
            "intrigerend*", "irritant*", "kwetsend*",
            "leerrijk*", "leerzaam*", "leesbaar", "levensecht*",
            "meeslepend*", "opwindend*", "ontwapenend*",
            "ongeloofwaardig*", "onvergetelijk*", "onverwacht*",
            "pakkend*", "poëtisch*", "prettig*", "raadselachtig*",
            "schokkend*", "schurend*", "spannend*", "sympathiek*",
            "teleurstellend*", "treffend*",
            "verbluffend*", "verhelderend*", "vernieuwend*", "verpletterend*",
            "verslavend*", "verstikkend*",
            "vertrouwd*", "vervelend*", "voelbaar*",
            "zalig*", "zenuwslopend*",
            # Terms below are from the verhalensite
            "adembenemend*", "actueel*", "absurd*", "bombastisch*", "bloedstollend*",
            "claustrofobisch*", "creepy*", "chapeau*", "cool*", "euforisch*",
            "fantastisch*", "fijn*", "fijne*", "flauw*", "fraai*",
            "gaaf*", "geinig*", "geniaal*", "geweldig*", "grappig*", "gruwelijk*",
            "hartstikke*", "heerlijk*", "heerlijke*", "heftig*",
            "helaas", "hoopgevend*", "huiveringwekkend*",
            "informatief*", "innemend*", "intriest*", "jammer*", "knap*",
            "langdradig*", "leuk*", "leuke*", "luguber*", "misplaatst*", "mooi*", "mooie*", "moois*",
            "oppervlakkig*", "originele*", "onthutsend*", "ontluisterend*",
            "ontroerend*", "ontzettend*", "onwijs*", "overtuigend*",
            "overzichtelijk*",
            "pijnlijk*", "plezant*", "plezierig*",
            "pracht*", "prachtig*", "prachtige*", "pregnant*", "proficiat*",
            "rustgevend*",
            "saai*", "schattig*", "schitterend*", "schrijnend*", "sfeervol*", "shockerend*",
            "slordig*", "spijtig*", "storend*", "subliem*", "super*",
            "tof*", "tragisch*", "triest*", "troosteloos*", "uitstekend*",
            "voorspelbaar*", "verschrikkelijk*", "verrassend*", "verwarrend*", "verbijsterend*",
            "verdiend*", "verdiende*", "vermakelijk*", "verrassend*", "vlot*", "voorspelbaar*",
            "zinderend*",
        ],
    },
    "adjective_term_reader_related": {
        "terms": [
            "bang*", "benauwd*", "benieuwd*", "beroerd*",
            "bewondering*", "bewust*", "blij*", "boos*",
            "dankbaar*", "doodsbenauwd*", "droevig*", "gelukkig*",
            "koud*", "kwaad*", "misselijk*",
            "nieuwsgierig*", "onrustig*", "stil*", "verdrietig*",
            "warm*", "woedend*",  "zenuwachtig*",
        ],
    },
    "noun_continuous_phrase": {
        "terms": [
            "als een trein",
            "educatieve waarde",
            "eye opener",
            "geen fan van",
            "in (een|één) zucht",
            "in (zijn|z'n|haar|m'n|mijn|je) (greep|grip)",
            "knoop in (me|mijn|m'n|je) maag",
            "meer dan waard",
            "op (grootse|niet mis te verstane) wijze",
            "(kromme tenen)",
            "op het puntje van (me|mijn|m'n|je) stoel",
            "verplichte kost",
            "voer voor",
            "zucht van verlichting",
        ],
    },
    "noun_discontinuous_phrase": {
        "terms": [
            "(brok) (in) (me|mijn|m'n|je) (keel)",
            "(alle moeite|de moeite) (waard)",
            "(tranen) (in) (de|me|mij|mijn|m'n) (ogen)",
        ],
    },
    "noun_term_book_related": {
        "terms": [
            "aanrader",
            "afbreuk", "afkeer", "bewondering", "boodschap",
            "compliment*",
            "cliche*",
            "gemis", "kriebels", "levensles", "levenslessen", "mokerslag",
            "overtuiging", "parel", "pareltje", "sneltreinvaart", "spanning",
            "teleurstelling", "verademing", "verrassing", "verrijking",
            "zonde",
        ],
    },
    "noun_term_reader_related": {
        "terms": [ # ik krijg X OR het geeft me
            "argwaan", "buikpijn", "energie",
            "herkenning",
            "hoofdpijn", "inspiratie", "jeuk", "kippenvel",
            "kriebel",
            "lachsalvo's",
            "medelijden", "nieuwsgierigheid", "ontzag", "rillingen", "spijt",
            "sympathie", "worsteling",
            "zenuwen",
        ],
    },
    "verb_continuous_phrase": {
        "terms": [
            "(bedenk|bedacht) (me)",
            "betekenis (krijgt|krijgen)",
            "de ogen doen openen",
            "(dit|dat|het) geeft",
            "doet me veel",
            "(dwong|dwongen|dwingt|dwingen) (me|mij|je|de lezer)",
            "gemakkelijk te lezen",
            "goed gedaan",
            "had wat mij betreft",
            "heen en weer geslingerd",
            "heeft me zoveel gedaan",
            "(hebben|heeft) ertoe geleid",
            "(hebben|heeft) ervoor gezorgd",
            "het schuurt", "het wringt", "het schrijnt",
            "het (lijkt|leek)", "(lijkt|leek) het",
            "(ik|je) (merk|merkt)",
            "(ik|je) weet nu",
            "(ik|je) (hoop|hoopt)",
            "leidt je naar de donkere hoeken van je eigen geest",
            "makkelijk geschreven",
            "niet meer stoppen",
            "stoppen met lezen",
            "te geloven",
            "(uitkijken|verlangen) naar",
            "zucht dicht",
        ],
    },
    "verb_discontinuous_phrase": {
        "terms": [
            "(anders|beter|negatiever|positiever|slechter|vrolijker|zonniger) (uitzien)",
            "(een andere) (bril|blik|kijk)",
            "(bij de keel) (grijpen|grijpt|greep|grepen|gegrepen)",
            "(blijft|blijven|bleef|bleven) (je|me|mij) (bij)",
            "(blijft|blijven) (een raadsel)",
            "(doet|doen) (me|mij|je) (denken aan)",
            "(doet|doen) (me|mij|je) (verlangen naar)",
            "(geeft|geven) (inzicht)",
            "(grijpt|grijpen|greep|grepen) (bij) (de|je|me|mijn|m'n) (keel)",
            "(houdt) (me|mij|je) (bij de les)",
            "(houdt|houden) (je|me|mijn|m'n) (aandacht) (vast)", "(houdt|houden|hield|hielden) (de lezer|me|mij|je) (bezig)",
            "(houdt|houden) (je|me|mij|de lezer) (vast)",
            "(mezelf|jezelf) (verliezen)",
            "(houdt|houden|hield|hielden) (me|mij|je|de lezer) (alert|scherp|geboeid|aan het lezen)",
            "(houdt|houden) (me|mij|je|de lezer) (uit) (m'n|mijn|je|zijn|z'n|haar|de) (slaap)",
            "(houdt|houden) (me|mij|je|de lezer|ons) (een spiegel voor)",
            "(houdt|houden) (me|mij|je|de lezer) (in een wurggreep|gekluisterd)",
            "(houdt|houden) (me|mij|je|de lezer) (in de ban|in haar ban|in haar macht|in zijn macht|in spanning|gespannen)",
            "(het) (nadeel) (is|blijft)",
            "(ik vind|vind ik) (het) (een) (boek)",
            "(ik wilde|je wilt|wil je) (weten)",
            "(in) (een|1) (adem|avond|keer|ruk|stuk|zucht) (gelezen|uitgelezen)",
            "(leest|las) (in) (een|1) (adem|avond|ruk|zucht) (uit)",
            "(komt|komen) (over)", "(komt|komen) (op) (me|mij) (over)",
            "(krijg|krijg) (geen|niet) (genoeg van)",
            "(liepen tranen|liepen de tranen|tranen liepen) (over mijn wangen)",
            "(maakt|maken) (duidelijk|inzichtelijk)",
            "(me|m'n|mijn|je) (hart) (gestolen)",
            "(gelezen) (moet|moeten) (hebben)",
            "(op) (zijn|haar|hun) (plek|plaats) (valt|vallen|viel|vielen)",
            "(moet) (diep|goed|lang|veel) (nadenken)",
            "(moet) (me|mijn|m'n|je) (hoofd) (erbij houden)",
            "(moet|moeten) lezen",
            "(staan de tranen) (me|mij|je) (in de ogen)",
            "(staan de tranen in) (me|mijn|m'n|je) (ogen)",
            "(spreekt|spreken|sprak|spraken) (me) (aan)",
            "(valt|vallen|viel|vielen) (op) (zijn|haar|hun) (plek|plaats)",
            "(wekt|wekken) (de indruk)", "(wekt|wekken) (de suggestie)",
            "(wordt) (lastiger)",
            "(worstel|worstelt|worstelen|worstelde|worstelden) (met|door)",
            "(zet|zetten|zette) (de lezer|je|me|mij) (aan het denken)",
            "(zet aan|aanzet) (tot nadenken)",
            "(zou|zouden) (moeten) (hebben|lezen)",
        ]
    },
    "verb_term": {
        "terms": [
            "aanbevelen", "aanraden",
            "bedenk", "indenken",
            "doorbreken",
            "ergeren", "irriteren", "storen",
            "boeien", "confronteren",
            "ergeren", "fascineren", "frustreren", "grijpen",
            "herkennen",
            "irriteren", "leren", "ontroeren", "storen",
            "verbazen", "verrijken", "vermaken", "vervelen",
            "genieten", "gniffelen", "grinniken", "huilen", "lachen", "meevoelen",
            "proeven",
            "afgeschrikt",
            "beloond", "bereikt", "bescheurd",
            "geboeid", "gechoqueerd", "geconfronteerd", "geergerd",
            "gefascineerd", "gefrustreerd", "gegrepen",
            "geinspireerd", "geirriteerd", "gekluisterd", "geleerd", "geprikkeld",
            "geraakt", "geschokt", "gestoord", "gekwetst",
            "meegesleurd", "meegesleept", "meegezogen", "meegenomen", "meegetrokken",
            "ondergedompeld", "onthecht", "ontroerd", "opgeroepen", "opgezogen",
            "overtuigt", "overtuigen",
            "teleurgesteld",
            "vermaakt", "verrast", "verbaasd", "verrijkt", "verveeld", "verpletterd",
            "gegniffeld", "gegrinnikt", "gehuild",
            "gelachen", "geleerd", "genoten",
            "verwacht",
            "bulderen", "geëmotioneerd", "gemist", "glimlachen", "knuffel",
            "meeleven", "meedenken", "meeslepen", "meezuigen", "meesleuren",
            "overdonderen",
            "schaterlachen", "shockeren", "stoorde", "stoort", "terugdenken aan",
            "verliezen", "verbazen", "vermaken", "vervelen",
            "verbijsteren", "verbijsterd", "verplaatsen", "wegleggen",
            "zeuren", "*zucht*",
        ],
    },
}

atomic_context_definitions = {
    "i_you": [r"\b(ik|je|jij)\b"],
    "me_you_reader": [r"\b(me|mij|mijn|m'n|je|jezelf|u|uzelf|ons|de lezer|lezers|zich)\b"],
    "adjective_reader_affect": [
        r"\b(ik|je) (ben|word|wordt|werd|raak|raakt|raakte) .*?\b{IMPACT_TERM}\b",
        r"\b(ik|je) .*?\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je) .*?\b{IMPACT_TERM}\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (er|hier) .*?\b{IMPACT_TERM} (van|door)\b",
        r"\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je|de lezer) (er|hier)(van| van|door| door)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (ben|bent|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(zal|zult|zullen) (er|hier) .*?\b{IMPACT_TERM}\b.*? (van|door) (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(zal|zult|zullen) .*? (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (zal|zult|zullen) (zijn|worden|raken)\b",
        r"\b(maakt|maken|maakte|maakten) (me|mij|je|de lezer) .*?\b{IMPACT_TERM}\b",
        r"\b(me|mij|je|de lezer) .*?\b{IMPACT_TERM}.*?\b(maakt|maken|maakte|maakten)\b",
        r"\b(krijg|krijgt|krijgen|kreeg) het .*?\b{IMPACT_TERM}\b",
        r"\b(voel|voelt|voelen|voelde) (me|mij|je) .*?\b{IMPACT_TERM}\b",
        r"\b{IMPACT_TERM}\b.*?(voel|voelt|voelen|voelde) (ik|je) (me|mij|je)\b",
        r"\b(me|mij|je) .*?\b{IMPACT_TERM} .*?\b(voel|voelt|voelen|voelde)\b",
        r"\been .*?{IMPACT_TERM}.*? gevoel\b",
    ],
    "book_aspect": [
        r"\b(\S*boek|\S*roman|\S*leesvoer|tekst|oeuvre|\S*bundel\S*)\b",
        r"\b(karakter\S*|personage\S*|hoofdperso\S*)\b",
        r"\b(ik-|hoofd|centrale|vader|moeder) *(figuur|figuren)\b", # can have one or more whitespaces
        r"\b(\S*verhaal|verhaallijn\S*|einde|situatie\S*|gebeurtenis\S*|plot|moment\S*|\S*passage\S*|\S*thema\S*)\b",
        r"\b(\S*portret\S*|tijdsbeeld|decor|\S*kroniek|\S*onderwerp\S*|\S*sfeer\S*)\b",
        r"\b(\S*stijl|verwoord\S*|taalgebruik|handelsmerk)\b",
        r"\b(\S*schrijver|\S*schrijfster|\S*auteur\S*)\b",
        r"\b(geschreven|schrijft|neerpennen|neergepend|opgetekend\S*)\b",
        r"\b(\S*schets\S*|tekenend|typer\S*|karakterise\S*|neerzetten|neergezet)\b",
        r"\b(afloop*|aflopen|climax|\S*element\S*|hoofdlijn\S*|hoogtepunt\S*|ontknoping\S*|opbouw\S*)\b",
        r"\b(relaas|stramien|\S*scene\S*|\S*scenario\S*|steekspel|slotakkoord|slotstuk|slot|waargebeurd)\b",
    ],
    "reading_aspect": [
        r"\b(lees|leest|lezen|las|lazen)\b",
    ],
}


def make_atomic_context_set(atomic_contexts):
    return [[definition] for context in atomic_contexts for definition in atomic_context_definitions[context]]

default_context_definitions = ["i_you", "me_you_reader", "book_aspect", "reading_aspect"]
impact_contexts = {
    "default": make_atomic_context_set(default_context_definitions),
    "adjective_term_reader_related": make_atomic_context_set(default_context_definitions + ["adjective_reader_affect"]),
}

