impact_groups = {
    "adjective_term_book_related": {
        "terms": [
            "aardig", "authentiek", "aangrijpend", "aansprekend",
            "beangstigend", "beklemmend", "benauwend", "boeiend",
            "choquerend", "confronterend", "deprimerend", "dreigend", "doodeng",
            "echt", "eentonig", "eerlijk", "eng",
            "fascinerend", "grappig", "gek",
            "hartverwarmend", "hartverscheurend", "herkenbaar", "hilarisch", "humoristisch",
            "indringend", "indrukwekkend", "inspirerend",
            "intrigerend", "kwetsend", "levensecht",
            "meeslepend", "opwindend", "ontwapenend", "onvergetelijk", "onverwacht",
            "pakkend", "poëtisch", "raadselachtig",
            "schokkend", "spannend", "sympathiek", "teleurstellend", "treffend",
            "verbluffend", "verslavend", "verpletterend", "vertrouwd", "vervelend", "voelbaar",
            "zalig", "zenuwslopend",
            # Terms below are from the verhalensite
            "adembenemend", "actueel", "absurd", "bombastisch", "bloedstollend",
            "claustrofobisch", "creepy", "chapeau", "cool", "euforisch",
            "fantastisch", "fijn", "fijne", "flauw", "fraai",
            "gaaf", "geinig", "geniaal", "geweldig", "grappige", "gruwelijk",
            "hartstikke", "heerlijk", "heerlijke", "heftig", "hoopgevend", "huiveringwekkend",
            "informatief", "innemend", "intriest", "jammer", "knap",
            "langdradig", "leuk", "leuke", "luguber", "misplaatst", "mooi", "mooie", "moois",
            "oppervlakkig", "originele", "onthutsend", "ontluisterend", "ontroerend", "onwijs",
            "pijnlijk", "pracht", "prachtig", "prachtige", "pregnant", "proficiat",
            "saai", "schattig", "schitterend", "schrijnend", "sfeervol", "shockerend",
            "slordig", "spijtig", "storend", "subliem", "super",
            "tof", "tragisch", "triest", "troosteloos", "uitstekend",
            "voorspelbaar", "verschrikkelijk", "verrassend", "verwarrend", "verbijsterend",
            "verdiend", "verdiende", "vermakelijk", "verrassend", "vlot", "voorspelbaar",
            "zinderend",
        ],
    },
    "adjective_term_reader_related": {
        "terms": [
            "bang", "benauwd", "benieuwd", "beroerd",
            "bewondering", "bewust", "blij", "boos",
            "doodsbenauwd", "droevig", "gelukkig",
            "koud", "kwaad", "misselijk",
            "nieuwsgierig", "onrustig", "stil", "verdrietig",
            "warm", "woedend",  "zenuwachtig",
        ],
    },
    "noun_phrase": {
        "terms": [
            "(kromme tenen)",
            "(tranen in) (de|mijn|m'n) ogen",
            "in (zijn|z'n|haar|m'n|mijn|je) (greep|grip)",
            "(op het puntje van) (mijn|m'n|je) stoel",
            "knoop in je maag", "in een zucht", "in één zucht", "zucht van verlichting",
        ],
    },
    "noun_term_book_related": {
        "terms": [
            "teleurstelling", "verademing", "verrassing", "verrijking",
            "afbreuk", "afkeer", "bewondering", "compliment", "complimenten",
            "gemis", "kriebels", "mokerslag", "pareltje", "sneltreinvaart", "zonde",
        ],
    },
    "noun_term_reader_related": {
        "terms": [ # ik krijg X OR het geeft me
            "argwaan", "buikpijn", "energie", "hoofdpijn", "inspiratie", "kippenvel",
            "medelijden", "nieuwsgierigheid", "ontzag", "rillingen", "spijt", "sympathie", "zenuwen",
            "kriebel", "jeuk",
        ],
    },
    "verb_phrase": {
        "terms": [
            "(doet|doen) (me|je) (denken aan)", "(doet|doen) (me|je) (verlangen naar)",
            "(komt|komen) over", "(komt|komen) op (me|mij) over",
            "(krijg|krijg) (geen|niet) (genoeg van)",
            "(staan de tranen) (me|mij|je) (in de ogen)", "(staan de tranen in) (mijn|m'n|je) ogen",
            "(liepen tranen|liepen de tranen|tranen liepen) (over mijn wangen)",
            "(houdt je vast)", "gekluisterd", "houdt (me|mij|je) (bij de les)",
            "(bij de keel) (grijpen|grijpt)", "(spreekt me aan)",
            "(blijft|blijven) (je bij)", "(zet|zetten) je (aan het denken)", "(zet aan|aanzet) (tot nadenken)",
            "(houdt je aandacht vast)", "houdt (me|mij|je) bezig",
            "(wekt|wekken) (de indruk)", "(wekt|wekken) (de suggestie)",
            "(mezelf|jezelf) verliezen",
            "(houdt|houden) (me|mij|je|de lezer) (alert|scherp|geboeid|aan het lezen)",
            "(houdt|houden) (me|mij|je|de lezer) uit (m'n|mijn|je|zijn|z'n|haar|de) slaap",
            "(houdt|houden) (me|mij|je|de lezer|ons) (een spiegel voor)",
            "(houdt|houden) (me|mij|je|de lezer) (in een wurggreep|gekluisterd)",
            "(houdt|houden) (me|mij|je|de lezer) (in de ban|in haar ban|in haar macht|in zijn macht|in spanning|gespannen)",
            "(heen en weer geslingerd)",
            "doet me veel", "heeft me zoveel gedaan", "het schuurt", "het wringt", "het schrijnt",
            "leidt je naar de donkere hoeken van je eigen geest.", "dwingt je", "(dwong|dwingt) me", "(zucht dicht)",
        ],
    },
    "verb_term": {
        "terms": [
            "ergeren", "irriteren", "storen",
            "verliezen", "verbazen", "vermaken", "vervelen",
            "boeien", "confronteren",
            "ergeren", "fascineren", "frustreren", "grijpen",
            "irriteren", "leren", "ontroeren", "storen",
            "verbazen", "verrijken", "vermaken", "vervelen",
            "genieten", "gniffelen", "grinniken", "huilen", "lachen", "meevoelen",
            "proeven", "uitkijken naar",
            "verlangen naar",
            "afgeschrikt",
            "beloond", "bereikt", "bescheurd",
            "geboeid", "gechoqueerd", "geconfronteerd", "geergerd", "gefascineerd", "gefrustreerd", "gegrepen",
            "geinspireerd", "geirriteerd", "geleerd", "geprikkeld",
            "geraakt", "geschokt", "gestoord", "gekwetst",
            "meegesleurd", "meegesleept", "meegezogen", "meegenomen",
            "ondergedompeld", "onthecht", "ontroerd", "opgeroepen", "opgezogen",
            "teleurgesteld",
            "vermaakt", "verrast", "verbaasd", "verrijkt", "verveeld", "verpletterd",
            "gegniffeld", "gegrinnikt", "gehuild",
            "gelachen", "geleerd", "genoten",
            "verwacht",
            "bulderen", "geëmotioneerd", "gemist", "glimlachen", "knuffel",
            "meeleven", "meedenken", "overdonderen",
            "schaterlachen", "shockeren", "stoorde", "stoort", "terugdenken aan",
            "verbijsteren", "verbijsterd", "verplaatsen", "zeuren", "*zucht*",
        ],
    },
}

atomic_context_definitions = {
    "i_you": [r"\b(ik|je|jij)\b"],
    "me_you_reader": [r"\b(me|mij|mijn|m'n|je|jezelf|u|uzelf|ons|de lezer|lezers|zich)\b"],
    "adjective_reader_affect": [
        r"\b(ik|je) (ben|word|wordt|werd|raak|raakt|raakte) .*?\b{IMPACT_TERM}\b",
        r"\b(ik|je) .*?\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je) .*?\b{IMPACT_TERM}\b",
        r"\b(ben|word|wordt|werd|raak|raakt|raakte) (er|hier) .*?\b{IMPACT_TERM} (van|door)\b",
        r"\b{IMPACT_TERM} .*?\b(ben|word|wordt|werd|raak|raakt|raakte) (ik|je|de lezer) (er|hier)(van| van|door| door)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (ben|bent|word|wordt|werd|raak|raakt|raakte)\b",
        r"\b(zal|zult|zullen) (er|hier) .*?\b{IMPACT_TERM}\b.*? (van|door) (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(zal|zult|zullen) .*? (zijn|worden|raken)\b",
        r"\b{IMPACT_TERM} .*?\b(van|door) (zal|zult|zullen) (zijn|worden|raken)\b",
        r"\b(maakt|maken|maakte|maakten) (me|mij|je|de lezer) .*?\b{IMPACT_TERM}\b",
        r"\b(me|mij|je|de lezer) .*?\b{IMPACT_TERM}.*?\b(maakt|maken|maakte|maakten)\b",
        r"\b(krijg|krijgt|krijgen|kreeg) het .*?\b{IMPACT_TERM}\b",
        r"\b(voel|voelt|voelen|voelde) (me|mij|je) .*?\b{IMPACT_TERM}\b",
        r"\b{IMPACT_TERM}\b.*?(voel|voelt|voelen|voelde) (ik|je) (me|mij|je)\b",
        r"\b(me|mij|je) .*?\b{IMPACT_TERM} .*?\b(voel|voelt|voelen|voelde)\b",
        r"\been .*?{IMPACT_TERM}.*? gevoel\b",
    ],
    "book_aspect": [
        r"\b(\S*boek|\S*roman|\S*leesvoer|tekst|oeuvre|\S*bundel\S*)\b",
        r"\b(karakter\S*|personage\S*|hoofdperso\S*)\b",
        r"\b(ik-|hoofd|centrale|vader|moeder) *(figuur|figuren)\b", # can have one or more whitespaces
        r"\b(\S*verhaal|verhaallijn\S*|einde|situatie\S*|gebeurtenis\S*|plot|moment\S*|\S*passage\S*|\S*thema\S*)\b",
        r"\b(\S*portret\S*|tijdsbeeld|decor|\S*kroniek|\S*onderwerp\S*|\S*sfeer\S*)\b",
        r"\b(\S*stijl|verwoord\S*|taalgebruik|handelsmerk)\b",
        r"\b(\S*schrijver|\S*schrijfster|\S*auteur\S*)\b",
        r"\b(geschreven|schrijft|neerpennen|neergepend|opgetekend\S*)\b",
        r"\b(\S*schets\S*|tekenend|typer\S*|karakterise\S*|neerzetten|neergezet)\b",
        r"\b(afloop*|aflopen|climax|\S*element\S*|hoofdlijn\S*|hoogtepunt\S*|ontknoping\S*|opbouw\S*)\b",
        r"\b(relaas|stramien|\S*scene\S*|\S*scenario\S*|steekspel|slotakkoord|slotstuk|slot|waargebeurd)\b",
    ],
    "reading_aspect": [
        r"\b(lees|leest|lezen|las|lazen)\b",
    ],
}


def make_atomic_context_set(atomic_contexts):
    return [[definition] for context in atomic_contexts for definition in atomic_context_definitions[context]]

default_context_definitions = ["i_you", "me_you_reader", "book_aspect", "reading_aspect"]
impact_contexts = {
    "default": make_atomic_context_set(default_context_definitions),
    "adjective_term_reader_related": make_atomic_context_set(default_context_definitions + ["adjective_reader_affect"]),
}

